name: Deploy to Azure
on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: document-portal-app
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

      - name: Optimize for deployment
        run: |
          # Remove dev dependencies and source maps
          rm -rf node_modules
          rm -rf .next/cache
          rm -rf .next/**/*.map

          # Install only production dependencies
          npm ci --only=production --ignore-scripts

          # Create standalone output
          mkdir -p .next/standalone
          cp -r .next/static .next/standalone/.next/
          cp -r public .next/standalone/
          cp package.json .next/standalone/

          # Create efficient deployment package
          cd .next/standalone
          zip -r ../../deploy.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip

      - name: Clean up and restart
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group document-portal-rg
