name: Deploy to Azure App Service

on:
  push:
    branches: [main, dev]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'prod' || 'dev') }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [ "${{ env.DEPLOY_ENV }}" == "prod" ]; then
            echo "AZURE_APP_NAME=${{ secrets.AZURE_PROD_APP_NAME }}" >> $GITHUB_ENV
            echo "Deploying to PRODUCTION environment"
          else
            echo "AZURE_APP_NAME=${{ secrets.AZURE_DEV_APP_NAME }}" >> $GITHUB_ENV
            echo "Deploying to DEVELOPMENT environment"
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ env.DEPLOY_ENV == 'prod' && 'latest' || 'dev-latest' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ env.DEPLOY_ENV == 'prod' && 'latest' || 'dev-latest' }}
          cache-to: type=inline

      - name: Login to Azure
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          images: ghcr.io/${{ github.repository }}:${{ env.DEPLOY_ENV == 'prod' && 'latest' || 'dev-latest' }}
